//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shadowsocks {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shadowsocks.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* eslint-disable */
        ///// Was generated by gfwlist2pac in precise mode
        ///// https://github.com/clowwindy/gfwlist2pac
        ///
        ///// 2019-10-06: More &apos;javascript&apos; way to interaction with main program
        ///// 2019-02-08: Updated to support shadowsocks-windows user rules.
        ///
        ///var proxy = __PROXY__;
        ///var userrules = [];
        ///var rules = [];
        ///
        ///// convert to abp grammar
        ///for (var i = 0; i &lt; __RULES__.length; i++) {
        ///    var s = __RULES__[i];
        ///    if (s.substring(0, 2) == &quot;||&quot;) s += &quot;^&quot;;
        ///    rules.push(s);
        ///}
        ///
        ///for (var i = 0; i &lt; __USERRULES__.len [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABP_JS {
            get {
                return ResourceManager.GetString("ABP_JS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DLC_DAT {
            get {
                object obj = ResourceManager.GetObject("DLC_DAT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to listen-address __PRIVOXY_BIND_IP__:__PRIVOXY_BIND_PORT__
        ///toggle 0
        ///logfile ss_privoxy.log
        ///show-on-task-bar 0
        ///activity-animation 0
        ///forward-socks5 / __SOCKS_HOST__:__SOCKS_PORT__ .
        ///max-client-connections 2048
        ///hide-console
        ///.
        /// </summary>
        internal static string PRIVOXY_CONF {
            get {
                return ResourceManager.GetString("PRIVOXY_CONF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PRIVOXY_EXE {
            get {
                object obj = ResourceManager.GetObject("PRIVOXY_EXE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ! Put user rules line by line in this file.
        ///! See https://adblockplus.org/en/filter-cheatsheet
        ///.
        /// </summary>
        internal static string USER_RULE {
            get {
                return ResourceManager.GetString("USER_RULE", resourceCulture);
            }
        }
    }
}
